
[[Client]]
Addr = "127.0.0.1:1080"
Timeout = 10
IdleTimeout = 120

#Type: Relay SOCKS(default)
Type = "SOCKS"

#Transparent forwarding Address
RelayTo = "192.168.0.1:3306"

[[Server]]
#Disable = true

#Type: NOPROXY SOCKS SHADOWSOCKS(default)
Type = "SHADOWSOCKS"

Addr = "127.0.0.1:1081"

#Cipher:
# UNENCRYPTED
# AES-128-GCM AES-192-GCM AES-256-GCM
# AES-128-CTR AES-192-CTR AES-256-CTR
# AES-128-CFB AES-192-CFB AES-256-CFB
# CHACHA20-POLY1305 CHACHA20-IETF XCHACHA20
Cipher = "AES-256-GCM"
Password = "123456"
DNS = []

#Proxy if Rules Not Match
Proxy = true

#Rules ["www.google.com", ".github.com"]
Rules = []
