
[[Client]]
Addr = "127.0.0.1:1080"
Timeout = 10
IdleTimeout = 120

#Type: SOCKS(default) RELAY SHADOWSOCKS
Type = "SOCKS"

#Transparent forwarding Address
RelayTo = "192.168.0.1:3306"

Forbid = ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

[[Client]]
Addr = "127.0.0.1:3306"
Type = "RELAY"
RelayTo = "192.168.0.1:3306"

[[Server]]
#Disable = true

#Type: SHADOWSOCKS(default) NATIVE SOCKS
Type = "SHADOWSOCKS"

Addr = "127.0.0.1:1081"

#Cipher:
# UNENCRYPTED
# AES-128-GCM AES-192-GCM AES-256-GCM
# AES-128-CTR AES-192-CTR AES-256-CTR
# AES-128-CFB AES-192-CFB AES-256-CFB
# CHACHA20-POLY1305 CHACHA20-IETF XCHACHA20
Cipher = "AES-256-GCM"
Password = "123456"
DNS = []

#Rules ["www.google.com", ".github.com"]
Rules = []
DefaultRule = true
