
Addr = "127.0.0.1:1080"

Timeout = 10

IdleTimeout = 120

#Cipher:
# UNENCRYPTED
# AES-128-GCM AES-192-GCM AES-256-GCM
# AES-128-CTR AES-192-CTR AES-256-CTR
# AES-128-CFB AES-192-CFB AES-256-CFB
# CHACHA20-POLY1305 CHACHA20-IETF XCHACHA20

[[Server]]
#Disable = true
Addr = "192.168.0.1"
Cipher = "UNENCRYPTED"
Passwd = ""
DNS = []
Proxy = false
Rules = ["www.google.com", ".github.com"]
